"use client";

import { useMemo, useState } from "react";
import { classInfo, studentDirectory } from "@/lib/data";
import { useApp } from "@/components/app-provider";
import { IconArrow, IconCheck, IconClock } from "@/components/icons";
import { Modal, ProgressBar, Toast, useToast } from "@/components/ui";

export default function TeacherPage() {
  const { closed, publishedLessons, lessons, stationOpen, activities, publishLesson, addLesson, closeStation, reopenStation } = useTeacherState();
  const [tab, setTab] = useState<"overview" | "lessons" | "students">("overview");
  const [addOpen, setAddOpen] = useState(false);
  const [subject, setSubject] = useState("Toán 7"); const [title, setTitle] = useState(""); const [week, setWeek] = useState("3"); const [objective, setObjective] = useState("");
  const { message, toast, dismiss } = useToast();
  const missing = studentDirectory.filter(s => !s.hasAllBooks).length;

  function downloadCsv() { const rows = [["ID","Học sinh","Đủ SGK","Tiến độ"], ...studentDirectory.map(s => [s.id, s.name, s.hasAllBooks ? "Có" : "Thiếu", `${s.progress}%`])]; const csv = rows.map(r => r.map(v => `"${v.replaceAll('"', '""')}"`).join(",")).join("\n"); const blob = new Blob(["\uFEFF" + csv], { type: "text/csv;charset=utf-8" }); const a = document.createElement("a"); a.href = URL.createObjectURL(blob); a.download = "tram-hoc-tam-students.csv"; a.click(); URL.revokeObjectURL(a.href); toast("Đã xuất danh sách học sinh dạng CSV."); }
  function submitLesson() { if (!title.trim() || !objective.trim()) return toast("Vui lòng nhập tên bài và mục tiêu."); addLesson({ subject, title, week: Number(week) || 1, objective }); setAddOpen(false); setTitle(""); setObjective(""); toast("Đã tạo Bản đồ bài học. Bạn có thể publish ngay trong danh sách."); }
  return <div className="mx-auto max-w-6xl space-y-6"><section className="rounded-[30px] border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><div className="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div><div className="text-xs font-bold uppercase tracking-[0.18em] text-slate-400">Góc giáo viên</div><h1 className="mt-2 text-3xl font-black tracking-tight sm:text-4xl">Điều phối Trạm Học Tạm</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-500">Theo dõi thiếu sách, tạo học liệu chuyển tiếp, kiểm soát publish và đóng trạm khi nguồn cung đủ.</p></div><div className={`rounded-3xl px-5 py-4 text-sm font-bold ${stationOpen ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-600"}`}>{stationOpen ? "Trạm đang hoạt động" : "Trạm đã đóng"}</div></div></section>
    <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Học sinh" value={classInfo.students.toString()} /><Metric label="Thiếu SGK" value={missing.toString()} /><Metric label="Bài đã publish" value={publishedLessons.length.toString()} /><Metric label="Audit events" value={activities.length.toString()} /></section>
    <div className="flex flex-wrap gap-2 rounded-2xl bg-white p-2 ring-1 ring-slate-200"><button onClick={() => setTab("overview")} className={tabBtn(tab === "overview")}>Tổng quan</button><button onClick={() => setTab("lessons")} className={tabBtn(tab === "lessons")}>Bài học</button><button onClick={() => setTab("students")} className={tabBtn(tab === "students")}>Học sinh</button></div>

    {tab === "overview" && <section className="grid gap-6 lg:grid-cols-[1fr_.85fr]"><div className="rounded-[28px] border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex items-center justify-between"><div><div className="text-xs font-bold uppercase tracking-[0.18em] text-slate-400">Kết thúc trạm</div><h2 className="mt-1 text-xl font-black">Đủ SGK → đóng chuyển tiếp</h2></div><IconClock className="h-5 w-5 text-slate-400" /></div><p className="mt-3 text-sm leading-6 text-slate-500">Trong MVP, việc đóng/mở được lưu ngay trong trình duyệt và ghi vào nhật ký hoạt động.</p><div className="mt-5 flex flex-wrap gap-2">{stationOpen ? <button onClick={() => { closeStation(); toast("Đã đóng Trạm Học Tạm."); }} className="inline-flex items-center gap-2 rounded-2xl bg-slate-900 px-4 py-3 text-sm font-bold text-white">Đóng Trạm Học Tạm <IconArrow className="h-4 w-4" /></button> : <button onClick={() => { reopenStation(); toast("Đã mở lại Trạm Học Tạm."); }} className="rounded-2xl bg-emerald-600 px-4 py-3 text-sm font-bold text-white">Mở lại trạm</button>}<button onClick={() => setAddOpen(true)} className="rounded-2xl border border-slate-200 px-4 py-3 text-sm font-bold">+ Tạo bài học</button><button onClick={downloadCsv} className="rounded-2xl border border-slate-200 px-4 py-3 text-sm font-bold">Xuất CSV</button></div></div><div className="card-grid-bg rounded-[28px] border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="text-xs font-bold uppercase tracking-[0.18em] text-slate-400">Audit log</div><div className="mt-5 space-y-3">{activities.map(item => <div key={item.id} className="rounded-2xl bg-white/90 p-3 text-sm font-semibold shadow-sm ring-1 ring-slate-100"><span className="mr-2 text-xs text-slate-400">{item.time}</span>{item.text}</div>)}</div></div></section>}

    {tab === "lessons" && <section className="rounded-[28px] border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex items-center justify-between gap-4"><div><div className="text-xs font-bold uppercase tracking-[0.18em] text-slate-400">Bài học chuyển tiếp</div><h2 className="mt-1 text-xl font-black">Publish học liệu tự biên soạn</h2></div><button onClick={() => setAddOpen(true)} className="rounded-2xl bg-slate-900 px-4 py-3 text-xs font-bold text-white">+ Tạo bài</button></div><div className="mt-5 overflow-hidden rounded-2xl border border-slate-200"><div className="hidden grid-cols-[1.2fr_.5fr_.35fr] bg-slate-50 px-4 py-3 text-[11px] font-bold uppercase tracking-wider text-slate-400 sm:grid"><span>Bài học</span><span>Nguồn</span><span>Trạng thái</span></div>{lessons.map(item => { const isPublished = publishedLessons.includes(item.id); return <div key={item.id} className="grid gap-3 border-t border-slate-100 px-4 py-4 text-sm sm:grid-cols-[1.2fr_.5fr_.35fr] sm:items-center"><div><div className="font-bold">{item.title}</div><div className="mt-1 text-xs text-slate-500">{item.subject} • Tuần {item.week}</div></div><div className="text-xs font-semibold text-slate-500">Tự biên soạn</div><div>{isPublished ? <span className="inline-flex items-center gap-1 rounded-full bg-emerald-50 px-2.5 py-1 text-[10px] font-black text-emerald-700"><IconCheck className="h-3.5 w-3.5" /> XANH</span> : <button onClick={() => { publishLesson(item.id); toast("Đã publish bài học."); }} className="rounded-xl bg-slate-900 px-3 py-2 text-[11px] font-bold text-white">Publish</button>}</div></div>; })}</div></section>}

    {tab === "students" && <section className="rounded-[28px] border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex items-end justify-between"><div><div className="text-xs font-bold uppercase tracking-[0.18em] text-slate-400">Theo dõi học sinh</div><h2 className="mt-1 text-xl font-black">Tình trạng SGK & tiến độ</h2></div><button onClick={downloadCsv} className="rounded-2xl border border-slate-200 px-3 py-2 text-xs font-bold">Xuất CSV</button></div><div className="mt-5 grid gap-3">{studentDirectory.map(s => <div key={s.id} className="grid gap-3 rounded-2xl border border-slate-200 p-4 sm:grid-cols-[1fr_auto_.7fr] sm:items-center"><div><div className="font-bold">{s.name}</div><div className="mt-1 text-xs text-slate-400">{s.id}</div></div><span className={`w-fit rounded-full px-2.5 py-1 text-[10px] font-black ${s.hasAllBooks ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-700"}`}>{s.hasAllBooks ? "Đủ SGK" : "Thiếu SGK"}</span><div><div className="mb-1 flex justify-between text-xs font-bold"><span>Tiến độ</span><span>{s.progress}%</span></div><ProgressBar value={s.progress} /></div></div>)}</div></section>}
    <Toast message={message} onClose={dismiss} />
    {addOpen && <Modal title="Tạo Bản đồ bài học" onClose={() => setAddOpen(false)} footer={<div className="flex justify-end gap-2"><button onClick={() => setAddOpen(false)} className="rounded-2xl border border-slate-200 px-4 py-3 text-sm font-bold">Hủy</button><button onClick={submitLesson} className="rounded-2xl bg-slate-900 px-4 py-3 text-sm font-bold text-white">Tạo bài</button></div>}><div className="space-y-4"><Field label="Môn"><select value={subject} onChange={e => setSubject(e.target.value)} className="field"><option>Toán 7</option><option>Ngữ văn 7</option><option>Khoa học tự nhiên 7</option><option>Lịch sử và Địa lí 7</option></select></Field><Field label="Tên bài"><input value={title} onChange={e => setTitle(e.target.value)} className="field" placeholder="Ví dụ: Tỉ lệ thức và dãy tỉ số bằng nhau" /></Field><Field label="Tuần"><input value={week} onChange={e => setWeek(e.target.value)} type="number" min="1" className="field" /></Field><Field label="Mục tiêu"><textarea value={objective} onChange={e => setObjective(e.target.value)} className="field min-h-28" placeholder="Mô tả mục tiêu cần đạt..." /></Field></div></Modal>}
  </div>;
}

function useTeacherState() { const { lessons, publishedLessons, activities, stationOpen, closeStation, reopenStation, publishLesson, addLesson } = useApp(); return { lessons, publishedLessons, activities, stationOpen, closeStation, reopenStation, publishLesson, addLesson, closed: !stationOpen }; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-[24px] border border-slate-200 bg-white p-5 shadow-sm"><div className="text-xs font-semibold text-slate-400">{label}</div><div className="mt-2 text-3xl font-black">{value}</div></div>; }
function tabBtn(active: boolean) { return `rounded-xl px-4 py-2 text-sm font-bold ${active ? "bg-slate-900 text-white" : "text-slate-600 hover:bg-slate-100"}`; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block"><span className="text-xs font-bold uppercase tracking-wide text-slate-500">{label}</span><div className="mt-1">{children}</div></label>; }
